name: mobile_pay_app_switch_flutter
description: A Flutter plugin for MobilePay
version: 0.0.2
homepage: https://github.com/Sebski123/mobile_pay_app_switch_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: mobilepay.dk.mobile_pay_flutter
    pluginClass: MobilePayFlutterPlugin

